# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DataUsage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DataUsage
    pod 'Alamofire', '~> 5.2'
    pod 'IHProgressHUD'

end


target 'DataUsageTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 5.2'

end
